### ISSUE TITLE
When it is time to run, it crashes

### ISSUE THREAD

**Issue by kootenpv** [LukeB42/Emissary#45]
pascal@MBP:~/Emissary $ cat feeds.txt

```
apikey: mykey

# url                                                 name            group            minute  hour    day     month   weekday
http://news.ycombinator.com/rss                       "HN"            "HN"             15!     *       *       *       *
http://phys.org/rss-feed/                             "Phys.org"      "Phys.org"       1       12      *       *       *
http://feeds.nature.com/news/rss/most_recent          "Nature"        "Nature"         30      13      *       *       *
```

Then ran

```
python -m emissary.run -c feeds.txt
```

And 

```
python -m emissary.run -d --cert cert --key key
```

without errors.

When it was time to run it produced:

```
 "Python quit unexpectedly while using the greenlet.so plug-in."
```

Tried relaunching in the same minute, and again immediately then hit the same error.

Python 2.7.10
greenlet.__version__ == '0.4.9'

**Comment by float64co** [comment]
Ok, what version of gevent are you using?

**Comment by kootenpv** [comment]
gevent.__version__ == '1.0.2'

**Comment by float64co** [comment]
If this fails to run I advise manually reinstalling Gevent: https://gist.github.com/LukeB42/7c0dd41de5e1e639fddb

**Comment by kootenpv** [comment]
Does not fail; reinstalled anyway.

**Comment by float64co** [comment]
OK good luck with it.

**Comment by kootenpv** [comment]
Still crashes.

**Comment by float64co** [comment]
You may have already seen this but some googling around turned up this: https://github.com/openyou/emokit/issues/136
Hope that helps

**Comment by kootenpv** [comment]
Unfortunately also doesn't work :( I really hoped that the latest dev version of `gevent` would do it. Perhaps I'll just run it on a VM then :)

**Comment by float64co** [comment]
Sorry to hear that. Good luck running it in a VM.
